name: yolo_env_py311
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.9.9=haa95532_0
  - expat=2.7.1=h8ddb27b_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.2=pyhc872135_1
  - python=3.11.14=h981015d_0
  - setuptools=80.9.0=py311haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py311haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - absl-py==2.3.1
      - accelerate==1.12.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.0
      - appdirs==1.4.4
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==25.4.0
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bitsandbytes==0.48.2
      - bleach==6.3.0
      - certifi==2025.11.12
      - cffi==2.0.0
      - cfgv==3.5.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - colorlog==6.10.1
      - comm==0.2.3
      - contourpy==1.3.3
      - cryptography==46.0.3
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - datasets==4.4.1
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - deprecated==1.3.1
      - dill==0.4.0
      - diskcache==5.6.3
      - distlib==0.4.0
      - distro==1.9.0
      - docling==2.65.0
      - docling-core==2.57.0
      - docling-ibm-models==3.10.3
      - docling-parse==4.7.2
      - docstring-parser==0.17.0
      - duckduckgo-search==8.1.1
      - et-xmlfile==2.0.0
      - evaluate==0.4.6
      - executing==2.2.1
      - faker==39.0.0
      - fastjsonschema==2.21.2
      - filelock==3.20.0
      - filetype==1.2.0
      - fonttools==4.60.1
      - fqdn==1.5.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - greenlet==3.3.0
      - grpcio==1.76.0
      - h11==0.16.0
      - h2==4.3.0
      - hpack==4.1.0
      - html2text==2025.4.15
      - httpcore==1.0.9
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - huggingface-hub==0.36.0
      - hyperframe==6.1.0
      - identify==2.6.15
      - idna==3.11
      - instructor==1.13.0
      - ipykernel==7.1.0
      - ipython==9.6.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jiter==0.11.1
      - joblib==1.5.2
      - jpype1==1.6.0
      - json5==0.12.1
      - jsonlines==4.0.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonref==1.1.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.10
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.15
      - kiwipiepy==0.22.1
      - kiwipiepy-model==0.22.0
      - kiwisolver==1.4.9
      - konlpy==0.6.0
      - koreanize-matplotlib==0.1.1
      - langchain==1.1.3
      - langchain-classic==1.0.0
      - langchain-community==0.4.1
      - langchain-core==1.1.3
      - langchain-experimental==0.4.0
      - langchain-huggingface==1.1.0
      - langchain-openai==1.1.1
      - langchain-qdrant==1.1.0
      - langchain-text-splitters==1.0.0
      - langchain-upstage==0.7.5
      - langgraph==1.0.4
      - langgraph-checkpoint==3.0.1
      - langgraph-prebuilt==1.0.5
      - langgraph-sdk==0.2.15
      - langsmith==0.4.58
      - lark==1.3.1
      - latex2mathml==3.78.1
      - levenshtein==0.27.3
      - llvmlite==0.46.0
      - lxml==6.0.2
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markdownify==1.2.2
      - marko==2.2.1
      - markupsafe==3.0.3
      - marshmallow==3.26.1
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - matplotlib-venn==1.1.2
      - mdurl==0.1.2
      - mistune==3.1.4
      - mpire==2.10.2
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - mypy-extensions==1.1.0
      - narwhals==2.13.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.5
      - nltk==3.9.2
      - nodeenv==1.10.0
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - numba==0.63.0
      - numpy==2.2.6
      - olefile==0.47
      - omegaconf==2.3.0
      - openai==2.14.0
      - opencv-python==4.12.0.88
      - openpyxl==3.1.5
      - orjson==3.11.5
      - ormsgpack==1.12.0
      - outcome==1.3.0.post0
      - overrides==7.7.0
      - packaging==23.2
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pdfminer-six==20251107
      - pdfplumber==0.11.8
      - pikepdf==10.0.2
      - pillow==11.3.0
      - platformdirs==4.5.0
      - plotly==6.5.0
      - pluggy==1.6.0
      - polars==1.34.0
      - polars-runtime-32==1.34.0
      - polyfactory==3.1.0
      - portalocker==3.2.0
      - pre-commit==4.5.1
      - primp==0.15.0
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==6.33.2
      - psutil==7.1.2
      - pure-eval==0.2.3
      - pyarrow==22.0.0
      - pyclipper==1.4.0
      - pycparser==2.23
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-settings==2.12.0
      - pygments==2.19.2
      - pylatexenc==2.10
      - pymupdf==1.26.6
      - pynndescent==0.5.13
      - pyparsing==3.2.5
      - pypdf==4.3.1
      - pypdfium2==4.30.0
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-docx==1.2.0
      - python-dotenv==1.2.1
      - python-json-logger==4.0.0
      - python-pptx==1.0.2
      - pytz==2025.2
      - pywin32==311
      - pywinpty==3.0.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - qdrant-client==1.16.1
      - ragas==0.4.1
      - rank-bm25==0.2.2
      - rapidfuzz==3.14.3
      - rapidocr==3.4.5
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.2.0
      - rouge-score==0.1.2
      - rpds-py==0.28.0
      - rtree==1.4.1
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - scikit-network==0.33.5
      - scipy==1.16.3
      - seaborn==0.13.2
      - selenium==4.39.0
      - semchunk==2.2.2
      - send2trash==1.8.3
      - sentence-transformers==5.1.2
      - shapely==2.1.2
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.8
      - sqlalchemy==2.0.45
      - stack-data==0.6.3
      - sympy==1.14.0
      - tabulate==0.9.0
      - tenacity==8.5.0
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tiktoken==0.12.0
      - tinycss2==1.4.0
      - tokenizers==0.22.1
      - torch==2.10.0.dev20251029+cu130
      - torchaudio==2.10.0.dev20251029+cu130
      - torchvision==0.25.0.dev20251029+cu130
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.57.3
      - tree-sitter==0.25.2
      - tree-sitter-c==0.24.1
      - tree-sitter-java==0.23.5
      - tree-sitter-javascript==0.25.0
      - tree-sitter-python==0.25.0
      - tree-sitter-typescript==0.23.2
      - trio==0.32.0
      - trio-websocket==0.12.2
      - ty==0.0.5
      - typer==0.19.2
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - ultralytics==8.3.222
      - ultralytics-thop==2.0.18
      - umap-learn==0.5.9.post2
      - uri-template==1.3.0
      - urllib3==2.6.1
      - uuid-utils==0.12.0
      - virtualenv==20.35.4
      - wcwidth==0.2.14
      - webcolors==24.11.1
      - webdriver-manager==4.0.2
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - widgetsnbextension==4.0.14
      - wordcloud==1.9.4
      - wrapt==2.0.1
      - wsproto==1.3.2
      - xlsxwriter==3.2.9
      - xxhash==3.6.0
      - yarl==1.22.0
      - zstandard==0.25.0
prefix: C:\Users\daboi\anaconda3\envs\yolo_env_py311
